### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by Vallista** [Wavez/react-hooks-lifecycle#2]
Hi, my name is Ballista, a programmer in Korea.
I think this article is good. So I'm going to translate it into Korean. Is it okay?

**Comment by Wavez** [comment]
sure thing :)

**Comment by Wavez** [comment]
@Vallista  can send the details once you'll finish and I'll link from both GitHub and medium to the translations.
Your efforts are appreciated 😊, thanks! looking forward.

**Comment by Vallista** [comment]
Okay. thx @Wavez !
I think I'll start working next week!
I'll give you a pr as soon as I'm done.
