### ISSUE TITLE
What about "new props updating" similar to the old diagram?

### ISSUE THREAD

**Issue by eladcandroid** [Wavez/react-hooks-lifecycle#3]
![image](https://user-images.githubusercontent.com/13297000/88058656-7058dd80-cb6c-11ea-87ee-68a2749d56c0.png)

**Comment by Wavez** [comment]
Sry for my late reply, for some reason I didn't get a notification for this issue.
It's a valid point, I should include that as well.
Thanks, will update.

**Comment by Wavez** [comment]
@all-contributors please add @eladcandroid for bug
