### ISSUE TITLE
Important to mention where cleanups are called in useEffect and useLayoutEffect

### ISSUE THREAD

**Issue by albseb511** [Wavez/react-hooks-lifecycle#5]
the cleanups are called at either unmounting or after everytime the dependency changes in the list of deps in the useEffect hook
It is called before the useEffect callback is called, but after the commit phase or dom updates
Many miss out this part

```
The clean-up function runs before the component is removed from the UI to prevent memory leaks. 
Additionally, if a component renders multiple times (as they typically do), 
the previous effect is cleaned up before executing the next effect. In our example, 
this means a new subscription is created on every update. 
```

the positioning of the text can improve i feel, if you feel the way its portrayed it clarifies a bit better let me know.

**Comment by albseb511** [comment]
raised a PR also on the same 
https://github.com/Wavez/react-hooks-lifecycle/pull/6

**Comment by Wavez** [comment]
Hey, thanks for ur contribution!
As the cleanup is not a lifecycle hook, but an internal process - I'm still unsure how to portrait it in the diagram.

**Comment by albseb511** [comment]
I think you should wrap it in around a box maybe for useEffect

before each new useEffect is called, it will make sure its cleaned up.
So its part of the useEffect hook either way

**Comment by Wavez** [comment]
@all-contributors please add @albseb511  for idea, bug, questions, example
